module.exports = {
  darkMode: 'class',
  content: [
    './content/**/*.{html,md}',
    './layouts/**/*.html',
    './themes/careercanvas/layouts/**/*.html',
    './themes/careercanvas/assets/js/**/*.js',
  ],
  theme: {
    extend: {
      colors: {
        bg: 'var(--color-bg)',
        'bg-secondary': 'var(--color-bg-secondary)',
        'bg-tertiary': 'var(--color-bg-tertiary)',
        primary: 'var(--color-primary)',
        'primary-light': 'var(--color-primary-light)',
        'primary-dark': 'var(--color-primary-dark)',
        'primary-lighter': 'var(--color-primary-lighter)',
        second: 'var(--color-second)',
        'second-light': 'var(--color-second-light)',
        'second-dark': 'var(--color-second-dark)',
        'second-lighter': 'var(--color-second-lighter)',
        third: 'var(--color-third)',
        'third-light': 'var(--color-third-light)',
        'third-dark': 'var(--color-third-dark)',
        'third-lighter': 'var(--color-third-lighter)',
        'third-darker': 'color-mix(in srgb, var(--color-third) 65%, black)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'text-tertiary': 'var(--color-text-muted)',
        'text-muted': 'var(--color-text-muted)',
        'border-primary': 'var(--color-border)',
        'border-secondary': 'var(--color-border-secondary)',
        'border-accent': 'var(--color-primary-light)',
      },
      fontFamily: {
        heading: ['Montserrat', 'Nunito Sans', 'sans-serif'],
        sans: ['Nunito Sans', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
};
